version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: together_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=together_db
      - MYSQL_USER=together
      - MYSQL_PASSWORD=together
      - MYSQL_ROOT_PASSWORD=together
    volumes:
      - db:/var/lib/mysql
    networks:
      - main

  auth:
    build: .
    container_name: together_auth
    restart: always
    ports:
      - "8585:8001"
    env_file:
      - .env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    depends_on:
      - mysql
    volumes:
      - .:/opt/app/
    networks:
      - main

networks:
  main:

volumes:
  db: