version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: together_mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=together_db
      - MYSQL_USER=together
      - MYSQL_PASSWORD=together
      - MYSQL_ROOT_PASSWORD=together
    volumes:
      - db:/var/lib/mysql
    networks:
      - main
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=together" ]
      interval: 5s
      timeout: 10s
      retries: 10

  auth:
    build: .
    container_name: together_auth
    restart: always
    ports:
      - "8001:8001"
    env_file:
      - .env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/opt/app/
    networks:
      - main

networks:
  main:

volumes:
  db: